
variables:
  imageName: 'k8s-demo'
  K8sPrevisionRequired: false

stages: 
- stage: Provisioning
  
  jobs:
  - job: Install
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'Dir'
      - task: PowerShell@2
        displayName: Terrafom Init
        inputs:
          targetType: 'inline'
          script: |
            # run terrafom 
            terraform init
          workingDirectory: './infra'
    
      - task: TerraformTaskV1@0
        condition: and(succeeded(), eq(variables.isMain, true))
        displayName: Terraform Validate and Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
          environmentServiceNameAzureRM: 'PayAsYouGo(f538d4ef-40d6-43bf-859c-e1d3e86f3667)'